spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-server
          uri: http://localhost:8080/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*),/$\{path}
            - CustomFilter

server:
  port: 8088
