server:
  port: 8088
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: USER_SERVER
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*),/$\{path}
        - id: AUTH_SERVER
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*),/$\{path}


