server:
  port: 8011
spring:
  application:
    name: auth-server
eureka:
  instance:
    hostname : auth-server
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
