server:
  port: 8011
spring:
  profiles:
    include: mysql
  application:
    name: auth-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secretKey: "thisIsSecretKey"
